integration test for openssl.cnf file
Signed-off-by: ashnamehrotra <ashnamehrotra@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -180,6 +180,30 @@ jobs:
           . .github/workflows/scripts/buildkitenvs/${{ matrix.buildkit_mode}}
           go test -v ./integration --addr="${COPA_BUILDKIT_ADDR}" --copa="$(pwd)/copa" -timeout 0
 
+  test-rpm-validation:
+    needs: test-patch-no-report
+    name: Test RPM validation
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    permissions: read-all
+    steps:
+        - name: Check RPM patched image for noreplace file
+          shell: bash
+          run: |
+            docker create --name test docker.io/sozercan/openssl:test-patched /bin/sh
+            tmp="$(mktmp)"
+            docker cp test:/etc/pki/tls/openssl.cnf "${tmp}"
+            
+            if ! grep -q foo "${tmp}"; then
+                echo "Error: openssl.cnf content replaced" >&2
+                rm "${tmp}"
+                docker rm -f test
+                exit 1
+            fi
+
+            rm "${tmp}"
+            docker rm -f test
+
   test-plugin:
     needs: build
     name: Test plugin
